---
# Deployment of our ansibletower-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansibletower-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: ansibletower-service
  replicas: 1
  template:
    metadata:
      labels:
        run: ansibletower-service
    spec:
      containers:
        - name: ansibletower-service
          image: keptnsandbox/ansibletower-service:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: EVENTBROKER
              value: "http://event-broker/keptn"
            - name: CONFIGURATION_SERVICE
              value: "http://configuration-service:8080"
            - name: ANSIBLETOWER_HOST
              valueFrom:
                secretKeyRef:
                  name: ansibletower
                  key: ansibletower-host
            - name: ANSIBLETOWER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ansibletower
                  key: ansibletower-token
        - name: distributor
          image: keptn/distributor:0.7.1
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.action.triggered'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
---
# Expose ansibletower-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: ansibletower-service
  namespace: keptn
  labels:
    run: ansibletower-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: ansibletower-service

